// 30 survey categories, 8 answers each. Each answer: [display text, points, ...extra accepted keywords]
// Guesses match an answer if they contain (or closely misspell) the answer or any of its keywords.
window.QUESTIONS = [
  { cat: "First Date Disasters", q: "Name something that would make a first date go terribly wrong", a: [
    ["Bad breath", 22, "breath", "smell", "smelly", "body odor", "bo", "stink", "stinky", "halitosis", "garlic", "bad hygiene", "hygiene", "sweaty", "farting", "fart", "gas"],
    ["Ex shows up", 18, "ex", "running into ex", "ex girlfriend", "ex boyfriend", "ex wife", "ex husband", "spouse shows up", "wife shows up", "husband shows up", "married", "they're married"],
    ["Spilling food", 14, "spill", "spilled", "spilling", "spilled drink", "spill wine", "mess", "food on shirt", "stain", "knocked over", "choking", "choke", "trip", "fall"],
    ["Being late", 12, "late", "show up late", "tardy", "stood up", "no show", "never showed", "ghosted", "cancel"],
    ["Forgot wallet", 10, "wallet", "can't pay", "cant pay", "no money", "broke", "card declined", "declined", "split the bill", "cheap", "didn't pay", "bill"],
    ["On their phone", 9, "phone", "texting", "cell", "social media", "ignoring you", "not listening", "distracted", "scrolling"],
    ["Rude to waiter", 8, "rude", "rude to server", "mean", "rude to staff", "yelling", "arrogant", "obnoxious"],
    ["Talking about ex", 7, "talk about ex", "talking about their ex", "complaining", "crying", "oversharing", "talking about themselves", "bragging"] ] },
  { cat: "Lies to the Boss", q: "Name a lie people tell their boss to get out of work", a: [
    ["I'm sick", 38, "sick", "ill", "flu", "cold", "fever", "covid", "throwing up", "vomiting", "migraine", "headache", "stomach", "not feeling well", "contagious", "strep", "virus"],
    ["Family emergency", 17, "emergency", "family", "family issue", "grandma", "grandmother", "mom", "dad", "relative", "hospital"],
    ["Car broke down", 12, "car trouble", "car", "flat tire", "flat", "no ride", "accident", "traffic", "battery died", "tow"],
    ["Doctor's appointment", 9, "doctor", "appointment", "dentist", "dr", "checkup", "physical", "surgery", "eye doctor", "medical"],
    ["Kid is sick", 8, "child sick", "kid", "kids", "child", "babysitter", "daycare", "school called", "son", "daughter", "no childcare"],
    ["Funeral", 7, "someone died", "death", "death in the family", "passed away", "died", "wake", "memorial"],
    ["Food poisoning", 5, "bad food", "ate something bad", "diarrhea", "stomach bug"],
    ["Power outage", 4, "power out", "internet down", "no power", "no internet", "wifi down", "pipe burst", "flood", "house flooded", "locked out", "plumber"] ] },
  { cat: "Ghost Hunters", q: "Name a sign that your house might be haunted", a: [
    ["Strange noises", 28, "noises", "noise", "sounds", "footsteps", "knocking", "banging", "creaking", "scratching", "bumps", "thumping", "music"],
    ["Lights flickering", 18, "lights", "light", "flickering", "flicker", "electricity", "tv turns on", "electronics", "lights turn on"],
    ["Doors opening", 14, "door", "doors", "door slamming", "doors closing", "slamming", "cabinets", "drawers", "windows open"],
    ["Cold spots", 11, "cold", "chill", "chills", "drafts", "draft", "temperature", "freezing", "breeze", "goosebumps"],
    ["Things moving", 10, "objects moving", "things fall", "stuff moves", "moving", "moved", "falling", "missing items", "things disappear", "furniture"],
    ["Pets acting weird", 8, "dog barking", "pets", "pet", "cat", "dog", "animals", "staring at nothing", "growling", "hissing"],
    ["Seeing a figure", 6, "ghost", "shadow", "shadows", "apparition", "figure", "spirit", "orbs", "person", "mirror", "reflection", "silhouette"],
    ["Voices", 5, "whispers", "whispering", "voice", "talking", "laughing", "crying", "screaming", "name called", "hearing your name", "singing"] ] },
  { cat: "Grandma's Purse", q: "Name something you'd find in your grandmother's purse", a: [
    ["Tissues", 26, "kleenex", "tissue", "hankie", "handkerchief", "napkin", "napkins", "paper towel", "wipes"],
    ["Candy", 20, "mints", "mint", "butterscotch", "peppermint", "peppermints", "hard candy", "caramel", "caramels", "werthers", "werther", "toffee", "lozenge", "cough drop", "cough drops", "gum", "chocolate", "lollipop", "sucker", "jolly rancher", "starlight", "tic tac", "tic tacs", "sweets", "snack", "snacks", "cookie"],
    ["Pills", 13, "medicine", "medication", "aspirin", "pill", "pill box", "pillbox", "tylenol", "advil", "prescription", "vitamins", "tums", "inhaler"],
    ["Lipstick", 11, "makeup", "lip stick", "compact", "powder", "chapstick", "lip balm", "perfume", "lotion", "hand cream", "comb", "brush", "mirror", "hairspray"],
    ["Coupons", 9, "coupon", "receipts", "receipt", "grocery list", "shopping list", "clippings"],
    ["Glasses", 8, "reading glasses", "eyeglasses", "spectacles", "sunglasses", "readers", "glasses case"],
    ["Wallet", 7, "money", "cash", "change", "coins", "change purse", "coin purse", "checkbook", "check book", "dollars", "credit card", "keys"],
    ["Photos", 6, "pictures", "picture", "photo", "grandkids", "grandkid", "grandchildren", "family photos"] ] },
  { cat: "Zombie Apocalypse", q: "Name something you'd grab first in a zombie apocalypse", a: [
    ["Weapon", 30, "gun", "guns", "shotgun", "rifle", "pistol", "bat", "baseball bat", "knife", "axe", "ax", "sword", "machete", "crossbow", "bow", "chainsaw", "crowbar", "hammer", "katana", "ammo", "bullets", "golf club", "shovel"],
    ["Food", 20, "canned food", "cans", "canned goods", "snacks", "rations", "beans", "granola bars", "mres", "jerky", "groceries"],
    ["Water", 15, "water bottle", "bottled water", "drinks", "water filter"],
    ["First aid kit", 9, "first aid", "medicine", "medical supplies", "bandages", "meds", "pills", "medkit", "antibiotics"],
    ["Family", 8, "kids", "wife", "husband", "loved ones", "children", "mom", "dad", "spouse", "partner", "pet", "dog", "friends"],
    ["Flashlight", 7, "light", "batteries", "lantern", "torch", "matches", "lighter"],
    ["Car keys", 6, "keys", "car", "truck", "gas", "fuel", "vehicle", "bike", "motorcycle"],
    ["Phone", 5, "radio", "charger", "walkie talkie", "walkie talkies", "cell phone"] ] },
  { cat: "Wedding Woes", q: "Name something that can go wrong at a wedding", a: [
    ["Bride or groom no-show", 24, "left at altar", "left at the altar", "no show", "runaway bride", "cold feet", "groom runs", "bride runs", "jilted", "called off", "doesn't show up", "says no", "bride", "groom", "cheating", "cheated"],
    ["Bad weather", 16, "rain", "raining", "storm", "weather", "wind", "snow", "hurricane", "too hot"],
    ["Someone objects", 14, "objection", "objects", "speak now", "interrupts"],
    ["Drunk guest", 12, "drunk", "drunk uncle", "drinking", "wasted", "bad toast", "embarrassing speech", "speech", "toast"],
    ["Dress gets ruined", 10, "dress", "torn dress", "stain", "ripped", "wardrobe malfunction", "tux", "wine spill", "spill"],
    ["Rings lost", 9, "ring", "rings", "lost ring", "forgot rings", "dropped ring"],
    ["Cake falls", 8, "cake", "cake fell", "food", "caterer", "food poisoning"],
    ["Fight breaks out", 7, "fight", "fighting", "brawl", "argument", "arguing", "drama", "mother in law", "family drama"] ] },
  { cat: "Teenage Rebellion", q: "Name something a teenager does that drives their parents crazy", a: [
    ["Talks back", 22, "back talk", "attitude", "sassy", "disrespect", "disrespectful", "mouthing off", "arguing", "argue", "yelling", "swearing", "cursing", "lying", "lies"],
    ["Always on phone", 20, "phone", "screen time", "texting", "social media", "tiktok", "instagram", "snapchat", "internet"],
    ["Messy room", 15, "messy", "doesn't clean", "dirty room", "mess", "clothes on floor", "dirty laundry", "room"],
    ["Breaks curfew", 12, "curfew", "stays out late", "sneaks out", "sneaking out", "out late", "comes home late", "partying", "party"],
    ["Sleeps all day", 10, "sleeps", "sleep", "sleeping in", "lazy", "stays up late", "won't wake up"],
    ["Won't do chores", 8, "chores", "doesn't help", "dishes", "won't help", "homework", "skips school", "grades", "bad grades"],
    ["Eye rolling", 7, "rolls eyes", "eye roll", "ignores", "ignoring", "sighing", "shrugging", "whatever"],
    ["Plays video games", 6, "video games", "gaming", "games", "fortnite", "xbox", "playstation", "minecraft", "roblox"] ] },
  { cat: "Desert Island", q: "Name something you'd want with you if stranded on a desert island", a: [
    ["Water", 24, "fresh water", "water filter", "drinks", "water bottle"],
    ["Food", 18, "snacks", "canned food", "fishing pole", "fishing rod", "net"],
    ["Knife", 14, "machete", "pocket knife", "swiss army knife", "axe", "multitool", "multi tool", "blade", "tools"],
    ["Lighter", 11, "matches", "fire", "flint", "fire starter", "magnifying glass"],
    ["Phone", 10, "satellite phone", "radio", "flare", "flares", "gps", "cell phone"],
    ["Spouse", 9, "partner", "wife", "husband", "friend", "best friend", "family", "girlfriend", "boyfriend", "volleyball", "wilson", "dog", "pet"],
    ["Boat", 8, "raft", "canoe", "kayak", "plane", "helicopter", "paddle"],
    ["Tent", 6, "shelter", "tarp", "blanket", "sleeping bag", "hammock", "hut"] ] },
  { cat: "Supervillain School", q: "Name something every supervillain needs", a: [
    ["Evil lair", 26, "lair", "hideout", "base", "volcano", "castle", "headquarters", "hq", "secret base", "underground"],
    ["Henchmen", 20, "minions", "minion", "sidekick", "army", "goons", "henchman", "crew", "followers", "robots"],
    ["Evil laugh", 14, "laugh", "maniacal laugh", "cackle", "mwahaha", "muahaha", "catchphrase", "monologue"],
    ["Cape", 11, "costume", "mask", "suit", "helmet", "outfit", "black clothes", "scar"],
    ["Superpower", 10, "powers", "power", "super power", "magic", "abilities"],
    ["Evil plan", 9, "plan", "scheme", "plot", "world domination", "take over the world", "doomsday device", "death ray", "laser", "weapon", "bomb"],
    ["Money", 6, "fortune", "rich", "riches", "cash", "funding", "gold", "diamonds"],
    ["Cat", 4, "white cat", "pet", "shark", "sharks", "pet shark", "pet cat", "nemesis", "hero", "arch enemy", "archenemy"] ] },
  { cat: "Airport Annoyances", q: "Name something that's annoying about flying", a: [
    ["Delays", 27, "delayed flight", "delay", "delayed", "cancellations", "cancelled", "canceled", "waiting", "layover", "layovers", "missed connection"],
    ["Security line", 19, "security", "tsa", "lines", "line", "pat down", "taking shoes off", "shoes", "body scanner", "liquids"],
    ["Crying baby", 14, "baby", "babies", "kids", "screaming kids", "crying", "screaming", "children", "child"],
    ["Lost luggage", 11, "luggage", "bags", "baggage", "suitcase", "bag fees", "checked bag", "baggage claim", "carry on"],
    ["Small seats", 10, "no legroom", "legroom", "leg room", "cramped", "seats", "seat", "middle seat", "small", "tight", "armrest", "uncomfortable"],
    ["Seat kicker", 7, "kicking seat", "kicking", "reclining", "recline", "rude passengers", "passengers", "loud passenger", "smelly passenger", "talker"],
    ["Turbulence", 7, "bumpy", "shaking", "rough flight", "ears popping", "ears"],
    ["Expensive food", 5, "food", "prices", "expensive", "price", "tickets", "airline food", "no food", "snacks", "pretzels"] ] },
  { cat: "Bad Roommates", q: "Name something a terrible roommate does", a: [
    ["Doesn't clean", 28, "messy", "dirty", "dirty dishes", "dishes", "mess", "slob", "never cleans", "trash", "garbage", "leaves mess"],
    ["Eats your food", 22, "steals food", "food", "eats food", "drinks your", "takes food", "groceries"],
    ["Loud", 13, "noisy", "loud music", "parties", "party", "noise", "music", "yelling", "snoring", "stays up late", "tv loud"],
    ["Doesn't pay rent", 12, "rent", "bills", "money", "late rent", "won't pay", "utilities", "owes money"],
    ["Brings people over", 9, "guests", "boyfriend", "girlfriend", "strangers", "company", "visitors", "significant other", "friends over", "overnight guests"],
    ["Borrows stuff", 7, "takes stuff", "steals", "stealing", "borrowing", "borrows clothes", "takes things"],
    ["Bad hygiene", 5, "smells", "smell", "stinks", "doesn't shower", "hygiene", "smelly", "bo"],
    ["Uses your stuff", 4, "uses things", "uses my stuff", "shampoo", "toilet paper", "uses your things", "goes through your stuff", "snooping", "nosy"] ] },
  { cat: "Job Interview", q: "Name something you should never do in a job interview", a: [
    ["Be late", 25, "late", "show up late", "tardy", "arrive late", "no show"],
    ["Curse", 17, "swear", "swearing", "cussing", "cuss", "cursing", "bad language", "profanity"],
    ["Lie", 14, "lying", "lies", "exaggerate", "fake resume", "make stuff up"],
    ["Check your phone", 12, "phone", "texting", "answer phone", "cell phone", "phone ringing"],
    ["Dress badly", 10, "sloppy", "dress", "pajamas", "shorts", "dress inappropriately", "flip flops", "jeans", "wrinkled", "messy", "underdressed", "hygiene", "smell"],
    ["Badmouth old boss", 9, "trash talk", "bad mouth", "complain about boss", "talk bad", "badmouth", "complain", "complaining", "negative", "talk bad about old job"],
    ["Chew gum", 7, "gum", "eat", "eating", "smoke", "smoking", "drink", "drunk", "yawn", "fall asleep"],
    ["Ask about salary", 6, "salary", "money", "pay", "vacation", "time off", "benefits", "raise"] ] },
  { cat: "Crime Scene", q: "Name something a detective looks for at a crime scene", a: [
    ["Fingerprints", 34, "prints", "fingerprint", "finger prints", "hand print", "handprint"],
    ["Blood", 19, "dna", "blood spatter", "bloodstain", "saliva", "spit", "bodily fluids", "blood stains"],
    ["Weapon", 15, "gun", "knife", "murder weapon", "bullet", "bullets", "shell casing", "casings", "rope", "poison"],
    ["Footprints", 10, "shoe prints", "footprint", "shoeprint", "tracks", "boot print", "tire tracks"],
    ["Hair", 8, "fibers", "hair samples", "fiber", "strand", "skin", "trace evidence"],
    ["Witnesses", 6, "witness", "suspects", "suspect", "people", "camera", "security camera", "cctv", "video", "footage"],
    ["Clues", 5, "evidence", "clue", "note", "notes", "letter", "cigarette", "cigarette butt", "receipt"],
    ["Body", 3, "victim", "corpse", "dead body", "cause of death", "chalk outline", "motive"] ] },
  { cat: "Midlife Crisis", q: "Name something a person going through a midlife crisis buys", a: [
    ["Sports car", 44, "car", "convertible", "corvette", "porsche", "ferrari", "lamborghini", "mustang", "camaro", "red car", "fast car", "new car"],
    ["Motorcycle", 18, "harley", "harley davidson", "bike", "motorbike", "chopper", "dirt bike"],
    ["Boat", 10, "yacht", "jet ski", "speedboat", "speed boat"],
    ["New wardrobe", 8, "clothes", "leather jacket", "jacket", "skinny jeans", "jeans", "sneakers", "shoes", "jewelry", "gold chain", "outfit", "earring"],
    ["Hair plugs", 7, "toupee", "wig", "hair", "hair dye", "hair transplant", "rogaine", "hair implants"],
    ["Plastic surgery", 5, "botox", "surgery", "facelift", "face lift", "implants", "nose job", "tummy tuck", "liposuction", "lipo"],
    ["Gym membership", 4, "gym", "workout", "personal trainer", "trainer", "exercise equipment", "peloton", "supplements"],
    ["Tattoo", 4, "tattoos", "piercing", "piercings", "ink"] ] },
  { cat: "Dog Behavior", q: "Name something dogs do that would be weird if humans did it", a: [
    ["Sniff butts", 32, "sniff", "smelling butts", "sniffing", "smell butts", "sniff people", "smelling", "smell crotch", "crotch"],
    ["Lick themselves", 18, "licking", "lick", "lick people", "licking face", "clean themselves", "grooming"],
    ["Drink from toilet", 12, "toilet", "drink toilet water", "toilet water", "puddles", "drink from puddle"],
    ["Chase their tail", 10, "tail", "chasing tail", "chase", "chasing", "chase cars", "chase squirrels", "spin in circles", "spinning", "circles"],
    ["Pee on things", 9, "pee", "peeing", "mark territory", "lift leg", "pee outside", "pee on trees", "poop outside", "poop in yard", "poop on lawn"],
    ["Eat off the floor", 8, "eat poop", "eat garbage", "eat trash", "floor", "eating off floor", "beg", "begging", "eat from bowl", "steal food"],
    ["Bark at strangers", 6, "bark", "barking", "howl", "howling", "growl", "bark at mailman", "mailman", "bark at doorbell"],
    ["Hump legs", 5, "hump", "humping", "hump things", "scoot", "scooting", "roll in dirt", "roll in mud", "dig", "digging", "fetch", "play fetch"] ] },
  { cat: "Haunted Hotel", q: "Name something that would make you check out of a hotel immediately", a: [
    ["Bed bugs", 36, "bugs", "bedbugs", "bed bug", "roaches", "cockroaches", "cockroach", "rats", "mice", "rodents", "insects", "spiders", "fleas"],
    ["Dirty sheets", 18, "dirty", "stains", "stain", "filthy", "dirty room", "unclean", "dirty towels", "blood stains", "sheets"],
    ["Bad smell", 13, "smell", "smells", "stinks", "stinky", "smoke smell", "odor", "musty"],
    ["Ghost", 10, "haunted", "creepy", "ghosts", "spirits", "murder", "body", "dead body", "creepy staff"],
    ["Mold", 8, "mildew", "water damage", "leak", "leaking", "fungus"],
    ["Hair in bathroom", 6, "hair", "dirty bathroom", "bathroom", "dirty toilet", "toilet", "shower", "dirty shower", "pubes"],
    ["No hot water", 5, "cold shower", "hot water", "no ac", "no air conditioning", "heat", "broken ac", "no wifi", "broken"],
    ["Noisy neighbors", 4, "noise", "loud", "noisy", "neighbors", "party", "screaming", "thin walls", "people next door"] ] },
  { cat: "Thanksgiving Dinner", q: "Name a topic you should avoid at Thanksgiving dinner", a: [
    ["Politics", 52, "election", "president", "trump", "biden", "democrats", "republicans", "voting", "government", "political"],
    ["Religion", 16, "god", "church", "religious", "faith", "beliefs", "atheism"],
    ["Money", 9, "salary", "income", "finances", "debt", "loans", "borrowing money", "inheritance", "will", "how much you make", "job", "jobs", "unemployment"],
    ["Relationships", 7, "dating", "love life", "marriage", "divorce", "boyfriend", "girlfriend", "when are you getting married", "kids", "having kids", "babies", "pregnancy", "sex life", "single"],
    ["Weight", 6, "diet", "getting fat", "fat", "appearance", "looks", "gained weight", "body", "eating too much"],
    ["Family drama", 5, "drama", "gossip", "family secrets", "secrets", "old fights", "past", "grudges", "in laws", "inlaws"],
    ["Exes", 3, "ex", "ex wife", "ex husband", "ex boyfriend", "ex girlfriend", "old flames"],
    ["Sex", 2, "sexuality", "birds and bees"] ] },
  { cat: "Witness Protection", q: "Name something you'd change about yourself if you entered witness protection", a: [
    ["Name", 34, "new name", "identity", "first name", "last name", "alias", "fake name"],
    ["Hair color", 22, "hair", "dye hair", "haircut", "hairstyle", "hair style", "shave head", "bald", "wig", "blonde", "dye"],
    ["Appearance", 12, "face", "plastic surgery", "looks", "nose", "surgery", "weight", "lose weight", "gain weight", "contacts", "eye color", "glasses", "tattoos"],
    ["Address", 9, "location", "move", "city", "home", "house", "state", "country", "where i live", "phone number", "number"],
    ["Accent", 7, "voice", "way i talk", "speech", "language"],
    ["Job", 6, "career", "occupation", "work", "profession"],
    ["Clothes", 5, "style", "wardrobe", "fashion", "outfit", "the way i dress"],
    ["Grow a beard", 5, "beard", "mustache", "moustache", "facial hair", "goatee", "shave", "shave beard"] ] },
  { cat: "Snooping", q: "Name something people secretly look at on their partner's phone", a: [
    ["Texts", 42, "messages", "text messages", "text", "texting", "imessage", "whatsapp", "chats", "conversations", "sms"],
    ["Photos", 16, "pictures", "camera roll", "gallery", "pics", "photo", "picture", "videos", "hidden photos"],
    ["Call log", 12, "calls", "recent calls", "call history", "phone calls", "who they called", "voicemail"],
    ["Social media", 10, "instagram", "facebook", "dms", "dm", "snapchat", "tiktok", "twitter", "likes", "followers", "following"],
    ["Contacts", 7, "contact list", "phone numbers", "numbers", "names"],
    ["Browser history", 6, "history", "search history", "internet history", "google", "searches", "websites"],
    ["Email", 4, "emails", "gmail", "inbox", "mail"],
    ["Dating apps", 3, "tinder", "bumble", "hinge", "apps", "dating app", "bank", "bank account", "location", "venmo"] ] },
  { cat: "Strange Superpowers", q: "Name a superpower people wish they had", a: [
    ["Flying", 32, "fly", "flight", "levitation", "levitate", "wings"],
    ["Invisibility", 22, "invisible", "disappear", "go invisible"],
    ["Teleportation", 14, "teleport", "teleporting", "be anywhere", "portals"],
    ["Mind reading", 11, "read minds", "telepathy", "reading minds", "mind control", "telekinesis", "read thoughts", "psychic"],
    ["Time travel", 8, "control time", "stop time", "freeze time", "rewind time", "time"],
    ["Super strength", 6, "strength", "strong", "super strong", "invincible", "invincibility", "indestructible"],
    ["Super speed", 4, "speed", "fast", "super fast", "running fast"],
    ["Healing", 3, "immortality", "immortal", "live forever", "heal", "healing powers", "regeneration", "never age", "shapeshifting", "shape shifting", "x ray vision", "laser eyes"] ] },
  { cat: "Restaurant Red Flags", q: "Name a sign that you should NOT eat at a restaurant", a: [
    ["It's empty", 26, "empty", "no customers", "no people", "nobody there", "no one there", "deserted", "dead"],
    ["Dirty", 22, "dirty tables", "filthy", "messy", "unclean", "dirty floors", "sticky", "dirty dishes", "dirty bathroom", "bathroom", "dirty silverware", "grease", "greasy"],
    ["Bugs", 14, "roaches", "cockroaches", "flies", "rats", "mice", "rodents", "bug", "insects", "ants"],
    ["Bad smell", 11, "smells", "smell", "stinks", "odor", "smells bad"],
    ["Bad reviews", 9, "reviews", "yelp", "one star", "low rating", "bad rating"],
    ["Health code rating", 8, "health grade", "health inspection", "failed inspection", "rating", "health code", "c rating", "grade", "shut down", "closed"],
    ["Sick staff", 6, "coughing", "rude staff", "staff", "sick", "employees", "cook", "no gloves", "rude", "bad service", "sneezing"],
    ["Hair in food", 4, "hair", "food", "cold food", "raw food", "undercooked", "bad food", "expired", "food poisoning"] ] },
  { cat: "Retirement Plans", q: "Name something people look forward to doing when they retire", a: [
    ["Travel", 40, "traveling", "travelling", "vacation", "cruise", "cruises", "see the world", "trip", "trips", "rv", "road trip"],
    ["Golf", 15, "golfing", "golf course"],
    ["Sleep in", 11, "sleep", "rest", "relax", "relaxing", "nothing", "do nothing", "nap", "naps", "no alarm"],
    ["Spend time with grandkids", 10, "grandkids", "family", "grandchildren", "kids", "spend time with family"],
    ["Fishing", 8, "fish", "go fishing", "hunting", "boating"],
    ["Gardening", 7, "garden", "yard work", "plants", "flowers"],
    ["Hobbies", 5, "crafts", "reading", "read", "knitting", "painting", "volunteer", "volunteering", "bingo", "cards", "pickleball", "woodworking", "hobby"],
    ["Move to Florida", 4, "florida", "move", "beach", "arizona", "warm weather", "retirement home", "lake house", "downsize"] ] },
  { cat: "Spy Gear", q: "Name a gadget you'd expect a secret agent to have", a: [
    ["Gun", 25, "pistol", "weapon", "silencer", "handgun", "tranquilizer", "dart gun", "sniper"],
    ["Hidden camera", 18, "camera", "spy camera", "tiny camera", "mini camera", "bug", "listening device", "wire", "recorder", "microphone"],
    ["Earpiece", 14, "radio", "communicator", "ear piece", "headset", "walkie talkie", "phone", "satellite phone"],
    ["Night vision goggles", 11, "night vision", "goggles", "glasses", "x ray glasses", "sunglasses", "binoculars", "infrared"],
    ["Laser watch", 10, "watch", "laser", "smart watch", "gadget watch"],
    ["Fake passport", 9, "passport", "fake id", "disguise", "id", "badge", "mask", "wig", "fake mustache"],
    ["Grappling hook", 7, "rope", "zipline", "jetpack", "jet pack", "parachute", "lock pick", "lockpick", "suction cups"],
    ["Exploding pen", 6, "pen", "explosives", "bomb", "grenade", "gum", "exploding gum", "tracker", "tracking device", "gps", "car", "fancy car", "aston martin"] ] },
  { cat: "Moving Day", q: "Name something that's hard to move when you change homes", a: [
    ["Piano", 30, "grand piano", "organ"],
    ["Couch", 25, "sofa", "sectional", "loveseat", "recliner", "futon", "furniture"],
    ["Fridge", 14, "refrigerator", "freezer", "stove", "oven", "appliances"],
    ["Bed", 10, "mattress", "bed frame", "bunk bed", "headboard", "box spring"],
    ["Dresser", 8, "wardrobe", "armoire", "cabinet", "bookcase", "bookshelf", "desk", "table", "dining table", "china cabinet", "entertainment center"],
    ["Washer and dryer", 6, "washer", "dryer", "washing machine", "laundry machine"],
    ["TV", 4, "television", "big screen", "flat screen"],
    ["Pool table", 3, "hot tub", "treadmill", "gym equipment", "safe", "aquarium", "fish tank"] ] },
  { cat: "Camping Fails", q: "Name something that could ruin a camping trip", a: [
    ["Rain", 32, "storm", "storms", "bad weather", "weather", "thunderstorm", "lightning", "flood", "snow", "cold", "wind"],
    ["Bugs", 22, "mosquitoes", "mosquitos", "mosquito", "bug bites", "ticks", "ants", "spiders", "insects", "bees", "flies"],
    ["Bears", 14, "bear", "wild animals", "animals", "snakes", "snake", "raccoons", "wolves", "skunk", "coyotes", "mountain lion"],
    ["Forgot the tent", 9, "tent", "broken tent", "leaky tent", "tent collapse", "forgot gear", "sleeping bag"],
    ["Getting lost", 8, "lost", "lost in the woods", "no map"],
    ["Poison ivy", 6, "poison oak", "rash", "sunburn", "injury", "getting hurt", "sick"],
    ["No food", 5, "forgot food", "food", "run out of food", "no water", "water"],
    ["Fire won't start", 4, "fire", "no fire", "wet wood", "forest fire", "wildfire", "no matches", "matches", "lighter"] ] },
  { cat: "Lazy Sunday", q: "Name something people do on a lazy Sunday", a: [
    ["Sleep in", 30, "sleep", "nap", "naps", "napping", "sleeping", "stay in bed", "lay in bed", "rest", "relax", "nothing"],
    ["Watch TV", 24, "tv", "binge", "netflix", "television", "movies", "movie", "binge watch", "shows", "hulu", "streaming", "couch"],
    ["Go to church", 12, "church", "pray", "mass", "worship"],
    ["Watch football", 10, "football", "sports", "nfl", "game", "watch the game", "basketball"],
    ["Eat brunch", 9, "brunch", "pancakes", "breakfast", "eat", "eating", "big breakfast", "takeout", "order food", "cook", "cooking"],
    ["Read", 6, "book", "reading", "newspaper", "paper", "magazine"],
    ["Stay in pajamas", 5, "pajamas", "pjs", "sweatpants", "robe", "don't get dressed"],
    ["Play video games", 4, "video games", "games", "gaming", "board games", "phone", "scroll", "social media"] ] },
  { cat: "Weird Phobias", q: "Name something a lot of people are secretly afraid of", a: [
    ["Spiders", 28, "spider", "tarantula", "arachnids", "bugs", "insects", "cockroaches"],
    ["Heights", 20, "falling", "high places", "tall buildings", "bridges"],
    ["Clowns", 14, "clown", "mimes", "dolls", "puppets", "mascots"],
    ["The dark", 11, "dark", "darkness", "night", "monsters", "ghosts", "under the bed"],
    ["Snakes", 10, "snake", "reptiles", "lizards"],
    ["Public speaking", 8, "speaking", "speeches", "speech", "talking in public", "crowds", "stage", "presentations", "embarrassment", "rejection", "being alone", "loneliness", "commitment"],
    ["Needles", 5, "shots", "injections", "doctor", "dentist", "blood", "hospitals"],
    ["Dying", 4, "death", "dying alone", "getting old", "aging", "flying", "planes", "water", "drowning", "ocean", "sharks", "small spaces", "tight spaces", "elevators"] ] },
  { cat: "Time Machine", q: "Name a time period people would visit with a time machine", a: [
    ["Dinosaurs", 30, "jurassic", "prehistoric", "dinosaur", "dino", "dinos", "stone age", "cavemen", "ice age"],
    ["The future", 22, "future", "year 3000", "2100", "100 years from now"],
    ["Ancient Egypt", 13, "egypt", "pyramids", "pharaohs", "cleopatra", "ancient times"],
    ["The 80s", 10, "80s", "1980s", "eighties", "70s", "1970s", "seventies", "90s", "1990s", "nineties", "disco"],
    ["Medieval times", 8, "middle ages", "knights", "medieval", "castles", "king arthur", "renaissance", "vikings"],
    ["Ancient Rome", 7, "rome", "romans", "roman empire", "gladiators", "ancient greece", "greece", "greeks", "caesar"],
    ["Their childhood", 6, "childhood", "high school", "my childhood", "when i was young", "past", "younger", "college", "wedding", "my birth", "my past"],
    ["The 60s", 4, "60s", "1960s", "woodstock", "50s", "1950s", "fifties", "sixties", "20s", "1920s", "roaring twenties", "civil war", "world war", "wild west", "old west", "jesus", "bible times", "biblical times"] ] },
  { cat: "Hospital Stay", q: "Name something people complain about when staying in the hospital", a: [
    ["Food", 38, "bad food", "hospital food", "jello", "jell o", "meals"],
    ["Can't sleep", 15, "sleep", "woken up", "waking up", "no sleep", "nurses waking you", "wake you up", "vitals", "no rest"],
    ["The gown", 12, "gown", "hospital gown", "clothes", "open back", "butt showing", "exposed"],
    ["Bed", 10, "uncomfortable bed", "beds", "pillows", "uncomfortable", "room", "roommate"],
    ["Needles", 8, "shots", "iv", "blood draws", "blood work", "pokes", "pain", "tests", "catheter", "bedpan"],
    ["The bill", 7, "cost", "expensive", "bill", "bills", "price", "insurance", "money", "parking"],
    ["Noise", 6, "beeping", "machines", "loud", "noisy", "alarms", "monitors"],
    ["Boredom", 4, "bored", "boring", "nothing to do", "tv", "wifi", "waiting", "wait", "doctors", "nurses", "visitors", "visiting hours", "cold", "smell"] ] },
  { cat: "Bad Neighbors", q: "Name something your neighbor does that would make you want to move", a: [
    ["Loud music", 30, "loud", "noise", "noisy", "music", "parties", "party", "partying", "bass", "loud tv", "construction", "lawn mower", "early morning"],
    ["Barking dog", 20, "dog", "dogs", "barking", "pets", "pet poop", "dog poop", "roosters", "animals"],
    ["Nosy", 13, "snooping", "spying", "gossip", "gossiping", "watching", "staring", "nosey", "peeping", "nosiness"],
    ["Messy yard", 11, "junk", "yard", "trash", "lawn", "garbage", "messy", "dirty", "junk cars", "tall grass", "weeds", "mess", "christmas lights"],
    ["Parks in your spot", 9, "parking", "blocks driveway", "parks", "driveway", "parks in front", "car"],
    ["Fighting", 7, "yelling", "arguing", "screaming", "fights", "domestic", "cops", "police", "drama"],
    ["Smoking", 6, "smoke", "weed", "cigarettes", "smell", "bbq smoke", "drugs", "drug dealing"],
    ["Borrows things", 4, "borrowing", "borrows", "steals", "stealing", "takes stuff", "trespassing", "comes over uninvited", "unannounced", "drops by", "won't leave"] ] },
];
